 export { Container } from './container'
 export { Rewiews } from './rewiews'
 export { SectionTitle } from './section-title'
export { Prices } from './prices'
export { NavLinksWithScroll } from './nav-links-with-scroll'
export { Curtain } from './curtain'
