export { Container } from './container'
export { Reviews } from './reviews'
export { SectionTitle } from './section-title'
export { Prices } from './prices'
export { NavLinksWithScroll } from './nav-links-with-scroll'
export { Curtain } from './curtain'
