import type { Metadata } from 'next'
import { Caveat } from 'next/font/google'
import './globals.css'
import { Providers } from '@/shared/components/providers'
import { Header, Footer } from '@/widgets'
import { ScrollSmootherProvider } from '@/shared/components/providers/scroll-smoother'
import { Container } from '@/shared/components'
const caveat = Caveat({
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon/jpg" href="icon.jpg" />
      </head>
      <body
        className={`${caveat.className} antialiased flex flex-col min-h-screen relative `}
      >
        <Providers>
          <Header />
          <ScrollSmootherProvider>
            <Container className="flex-1 min-h-screen pt-20">
              <main className="flex flex-col">{children}</main>
            </Container>
            <Footer />
          </ScrollSmootherProvider>
        </Providers>
      </body>
    </html>
  )
}
